version: '1'

services:
  api:
    image: qa_prediction_backend:1.0.0
    build: .
    command: sh -c "uvicorn backend.app:app --reload --port 8080 --host 0.0.0.0"
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - network-backend
  
  front:
    image: qa_prediction_frontend:1.0.0
    build: .
    command: sh -c " streamlit run ./frontend/main.py --server.port=8081"
    ports:
      - 8081:8081
    expose:
      - 8081
    networks:
      - network-backend


networks:
  network-backend:
